/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cic_localserver_UARTOperator */

#ifndef _Included_com_cic_localserver_UARTOperator
#define _Included_com_cic_localserver_UARTOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cic_localserver_UARTOperator
 * Method:    init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cic_localserver_UARTOperator_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_cic_localserver_UARTOperator
 * Method:    sendAndRetrieveMessage
 * Signature: (II[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cic_localserver_UARTOperator_sendAndRetrieveMessage
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_cic_localserver_UARTOperator
 * Method:    ackAndRetrieveMessage
 * Signature: (IIB[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cic_localserver_UARTOperator_ackAndRetrieveMessage
  (JNIEnv *, jclass, jint, jint, jbyte, jbyteArray);

/*
 * Class:     com_cic_localserver_UARTOperator
 * Method:    close
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_cic_localserver_UARTOperator_close
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
