// default package
// Generated Mar 26, 2015 3:44:56 PM by Hibernate Tools 3.4.0.CR1
package com.itu.bean;
/**
 * SmartMeter generated by hbm2java
 */
public class SmartMeter implements java.io.Serializable {

	private int smId;
	private int coordinatorId;
	private String smName;
	private byte[] smIeeeAddress;
	private String validation;

	public SmartMeter() {
	}

	public SmartMeter(int smId, int coordinatorId) {
		this.smId = smId;
		this.coordinatorId = coordinatorId;
	}

	public SmartMeter(int smId, int coordinatorId, String smName,
			byte[] smIeeeAddress, String validation) {
		this.smId = smId;
		this.coordinatorId = coordinatorId;
		this.smName = smName;
		this.smIeeeAddress = smIeeeAddress;
		this.validation = validation;
	}

	public int getSmId() {
		return this.smId;
	}

	public void setSmId(int smId) {
		this.smId = smId;
	}

	public int getCoordinatorId() {
		return this.coordinatorId;
	}

	public void setCoordinatorId(int coordinatorId) {
		this.coordinatorId = coordinatorId;
	}

	public String getSmName() {
		return this.smName;
	}

	public void setSmName(String smName) {
		this.smName = smName;
	}

	public byte[] getSmIeeeAddress() {
		return this.smIeeeAddress;
	}

	public void setSmIeeeAddress(byte[] smIeeeAddress) {
		this.smIeeeAddress = smIeeeAddress;
	}

	public String getValidation() {
		return this.validation;
	}

	public void setValidation(String validation) {
		this.validation = validation;
	}

}
