// default package
// Generated Mar 26, 2015 3:44:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * Coordinator generated by hbm2java
 */
public class Coordinator implements java.io.Serializable {

	private int coordinatorId;
	private int localServerId;
	private String coordinatorName;
	private byte[] coordinatorIeeeAddress;
	private String validation;

	public Coordinator() {
	}

	public Coordinator(int coordinatorId, int localServerId) {
		this.coordinatorId = coordinatorId;
		this.localServerId = localServerId;
	}

	public Coordinator(int coordinatorId, int localServerId,
			String coordinatorName, byte[] coordinatorIeeeAddress,
			String validation) {
		this.coordinatorId = coordinatorId;
		this.localServerId = localServerId;
		this.coordinatorName = coordinatorName;
		this.coordinatorIeeeAddress = coordinatorIeeeAddress;
		this.validation = validation;
	}

	public int getCoordinatorId() {
		return this.coordinatorId;
	}

	public void setCoordinatorId(int coordinatorId) {
		this.coordinatorId = coordinatorId;
	}

	public int getLocalServerId() {
		return this.localServerId;
	}

	public void setLocalServerId(int localServerId) {
		this.localServerId = localServerId;
	}

	public String getCoordinatorName() {
		return this.coordinatorName;
	}

	public void setCoordinatorName(String coordinatorName) {
		this.coordinatorName = coordinatorName;
	}

	public byte[] getCoordinatorIeeeAddress() {
		return this.coordinatorIeeeAddress;
	}

	public void setCoordinatorIeeeAddress(byte[] coordinatorIeeeAddress) {
		this.coordinatorIeeeAddress = coordinatorIeeeAddress;
	}

	public String getValidation() {
		return this.validation;
	}

	public void setValidation(String validation) {
		this.validation = validation;
	}

}
