// default package
// Generated Mar 26, 2015 3:44:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DataRegisterData generated by hbm2java
 */
public class DataRegisterData implements java.io.Serializable {

	private Integer dataRegisterRecordId;
	private int smId;
	private byte[] dataRegisterRecordValue;
	private Date localTimestamp;
	private Date serverTimestamp;

	public DataRegisterData() {
	}

	public DataRegisterData(int smId) {
		this.smId = smId;
	}

	public DataRegisterData(int smId, byte[] dataRegisterRecordValue,
			Date localTimestamp, Date serverTimestamp) {
		this.smId = smId;
		this.dataRegisterRecordValue = dataRegisterRecordValue;
		this.localTimestamp = localTimestamp;
		this.serverTimestamp = serverTimestamp;
	}

	public Integer getDataRegisterRecordId() {
		return this.dataRegisterRecordId;
	}

	public void setDataRegisterRecordId(Integer dataRegisterRecordId) {
		this.dataRegisterRecordId = dataRegisterRecordId;
	}

	public int getSmId() {
		return this.smId;
	}

	public void setSmId(int smId) {
		this.smId = smId;
	}

	public byte[] getDataRegisterRecordValue() {
		return this.dataRegisterRecordValue;
	}

	public void setDataRegisterRecordValue(byte[] dataRegisterRecordValue) {
		this.dataRegisterRecordValue = dataRegisterRecordValue;
	}

	public Date getLocalTimestamp() {
		return this.localTimestamp;
	}

	public void setLocalTimestamp(Date localTimestamp) {
		this.localTimestamp = localTimestamp;
	}

	public Date getServerTimestamp() {
		return this.serverTimestamp;
	}

	public void setServerTimestamp(Date serverTimestamp) {
		this.serverTimestamp = serverTimestamp;
	}

}
