// default package
// Generated Apr 6, 2015 2:49:25 PM by Hibernate Tools 3.4.0.CR1
package edu.itu.bean;
import java.util.Date;

/**
 * CommandLog generated by hbm2java
 */
public class CommandLog implements java.io.Serializable {

	private Integer id;
	private Integer commandId;
	private byte[] commandStream;
	private byte[] commandResult;
	private byte[] commandData;
	private byte[] commandStatus;
	private String generatedBy;
	private Date generatedTime;
	private Date executedTime;
	private Date lsdbInsertedTime;

	public CommandLog() {
	}

	public CommandLog(Integer commandId, byte[] commandStream,
			byte[] commandResult, byte[] commandData, byte[] commandStatus,
			String generatedBy, Date generatedTime, Date executedTime,
			Date lsdbInsertedTime) {
		this.commandId = commandId;
		this.commandStream = commandStream;
		this.commandResult = commandResult;
		this.commandData = commandData;
		this.commandStatus = commandStatus;
		this.generatedBy = generatedBy;
		this.generatedTime = generatedTime;
		this.executedTime = executedTime;
		this.lsdbInsertedTime = lsdbInsertedTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCommandId() {
		return this.commandId;
	}

	public void setCommandId(Integer commandId) {
		this.commandId = commandId;
	}

	public byte[] getCommandStream() {
		return this.commandStream;
	}

	public void setCommandStream(byte[] commandStream) {
		this.commandStream = commandStream;
	}

	public byte[] getCommandResult() {
		return this.commandResult;
	}

	public void setCommandResult(byte[] commandResult) {
		this.commandResult = commandResult;
	}

	public byte[] getCommandData() {
		return this.commandData;
	}

	public void setCommandData(byte[] commandData) {
		this.commandData = commandData;
	}

	public byte[] getCommandStatus() {
		return this.commandStatus;
	}

	public void setCommandStatus(byte[] commandStatus) {
		this.commandStatus = commandStatus;
	}

	public String getGeneratedBy() {
		return this.generatedBy;
	}

	public void setGeneratedBy(String generatedBy) {
		this.generatedBy = generatedBy;
	}

	public Date getGeneratedTime() {
		return this.generatedTime;
	}

	public void setGeneratedTime(Date generatedTime) {
		this.generatedTime = generatedTime;
	}

	public Date getExecutedTime() {
		return this.executedTime;
	}

	public void setExecutedTime(Date executedTime) {
		this.executedTime = executedTime;
	}

	public Date getLsdbInsertedTime() {
		return this.lsdbInsertedTime;
	}

	public void setLsdbInsertedTime(Date lsdbInsertedTime) {
		this.lsdbInsertedTime = lsdbInsertedTime;
	}

}
