// default package
// Generated Apr 6, 2015 2:49:25 PM by Hibernate Tools 3.4.0.CR1
package edu.itu.bean;
/**
 * LocalServer generated by hbm2java
 */
public class LocalServer implements java.io.Serializable {

	private int localServerId;
	private String localServerName;
	private byte[] localServerIeeeAddress;
	private String validation;

	public LocalServer() {
	}

	public LocalServer(int localServerId) {
		this.localServerId = localServerId;
	}

	public LocalServer(int localServerId, String localServerName,
			byte[] localServerIeeeAddress, String validation) {
		this.localServerId = localServerId;
		this.localServerName = localServerName;
		this.localServerIeeeAddress = localServerIeeeAddress;
		this.validation = validation;
	}

	public int getLocalServerId() {
		return this.localServerId;
	}

	public void setLocalServerId(int localServerId) {
		this.localServerId = localServerId;
	}

	public String getLocalServerName() {
		return this.localServerName;
	}

	public void setLocalServerName(String localServerName) {
		this.localServerName = localServerName;
	}

	public byte[] getLocalServerIeeeAddress() {
		return this.localServerIeeeAddress;
	}

	public void setLocalServerIeeeAddress(byte[] localServerIeeeAddress) {
		this.localServerIeeeAddress = localServerIeeeAddress;
	}

	public String getValidation() {
		return this.validation;
	}

	public void setValidation(String validation) {
		this.validation = validation;
	}

}
