// default package
// Generated Apr 6, 2015 2:49:25 PM by Hibernate Tools 3.4.0.CR1
package edu.itu.bean;
/**
 * MonitorConfig generated by hbm2java
 */
public class MonitorConfig implements java.io.Serializable {

	private Integer monitorConfigId;
	private Integer smLoadConfigId;
	private String paramName1;
	private String paramName2;

	public MonitorConfig() {
	}

	public MonitorConfig(Integer smLoadConfigId, String paramName1,
			String paramName2) {
		this.smLoadConfigId = smLoadConfigId;
		this.paramName1 = paramName1;
		this.paramName2 = paramName2;
	}

	public Integer getMonitorConfigId() {
		return this.monitorConfigId;
	}

	public void setMonitorConfigId(Integer monitorConfigId) {
		this.monitorConfigId = monitorConfigId;
	}

	public Integer getSmLoadConfigId() {
		return this.smLoadConfigId;
	}

	public void setSmLoadConfigId(Integer smLoadConfigId) {
		this.smLoadConfigId = smLoadConfigId;
	}

	public String getParamName1() {
		return this.paramName1;
	}

	public void setParamName1(String paramName1) {
		this.paramName1 = paramName1;
	}

	public String getParamName2() {
		return this.paramName2;
	}

	public void setParamName2(String paramName2) {
		this.paramName2 = paramName2;
	}

}
