package bean;
// default package
// Generated Apr 6, 2015 11:21:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * SmartMeterChannelConfig generated by hbm2java
 */
public class SmartMeterChannelConfig implements java.io.Serializable {

	private Integer smChannelId;
	private Integer smId;
	private byte[] smConfigCode;
	private String channelName0;
	private String channelName1;
	private String channelName2;
	private String channelName3;
	private String channelName4;
	private String channelName5;
	private String channelName6;
	private String channelName7;

	public SmartMeterChannelConfig() {
	}

	public SmartMeterChannelConfig(Integer smId, byte[] smConfigCode,
			String channelName0, String channelName1, String channelName2,
			String channelName3, String channelName4, String channelName5,
			String channelName6, String channelName7) {
		this.smId = smId;
		this.smConfigCode = smConfigCode;
		this.channelName0 = channelName0;
		this.channelName1 = channelName1;
		this.channelName2 = channelName2;
		this.channelName3 = channelName3;
		this.channelName4 = channelName4;
		this.channelName5 = channelName5;
		this.channelName6 = channelName6;
		this.channelName7 = channelName7;
	}

	public Integer getSmChannelId() {
		return this.smChannelId;
	}

	public void setSmChannelId(Integer smChannelId) {
		this.smChannelId = smChannelId;
	}

	public Integer getSmId() {
		return this.smId;
	}

	public void setSmId(Integer smId) {
		this.smId = smId;
	}

	public byte[] getSmConfigCode() {
		return this.smConfigCode;
	}

	public void setSmConfigCode(byte[] smConfigCode) {
		this.smConfigCode = smConfigCode;
	}

	public String getChannelName0() {
		return this.channelName0;
	}

	public void setChannelName0(String channelName0) {
		this.channelName0 = channelName0;
	}

	public String getChannelName1() {
		return this.channelName1;
	}

	public void setChannelName1(String channelName1) {
		this.channelName1 = channelName1;
	}

	public String getChannelName2() {
		return this.channelName2;
	}

	public void setChannelName2(String channelName2) {
		this.channelName2 = channelName2;
	}

	public String getChannelName3() {
		return this.channelName3;
	}

	public void setChannelName3(String channelName3) {
		this.channelName3 = channelName3;
	}

	public String getChannelName4() {
		return this.channelName4;
	}

	public void setChannelName4(String channelName4) {
		this.channelName4 = channelName4;
	}

	public String getChannelName5() {
		return this.channelName5;
	}

	public void setChannelName5(String channelName5) {
		this.channelName5 = channelName5;
	}

	public String getChannelName6() {
		return this.channelName6;
	}

	public void setChannelName6(String channelName6) {
		this.channelName6 = channelName6;
	}

	public String getChannelName7() {
		return this.channelName7;
	}

	public void setChannelName7(String channelName7) {
		this.channelName7 = channelName7;
	}

}
